### ISSUE TITLE
关于alloyimage.base.js中drawRect函数的有关问题

### ISSUE THREAD

**Issue by mapleeit** [AlloyTeam/AlloyImage#13]
最近在阅读`alloyImage`的源码，在`drawRect()`__（line：734）__函数中发现可能有以下两个问题：
- `var data = this.tempPsLib.imgData.data;`__（line：751）__其中`tempPsLib`在此函数中不存在，调试图如下：  

![2015-03-17 11 20 40](https://cloud.githubusercontent.com/assets/4194287/6690905/3052b944-ccfe-11e4-9475-6d6445bc0ef3.png)

- 彩色图的直方图一般情况下应该是把RGB三色通道分开做直方图的，而在本函数中是混在一起来算直方图。这种方式一般是不建议使用的。

**Comment by dorsywang** [comment]
感谢@mapleeit的建议 直方图的报错的问题明天我看下
另外，一起做直方图的例子也是有的，比如PS
![o](https://cloud.githubusercontent.com/assets/7475208/6691165/02ec3c80-cd00-11e4-9f4c-b7152e20aba8.jpg)

分开做确实会更，更能反映一定的问题，比如色调等

**Comment by mapleeit** [comment]
@dorsywang 哦，这个倒是我孤陋寡闻了，之前学的是分开的直方图。我觉得可以把这个函数稍微改一下，可传参选择直方图方式，然后默认选择四通道一起做的。感觉只有一起做的还是有点单薄~

**Comment by dorsywang** [comment]
修正了

**Comment by dorsywang** [comment]
https://github.com/AlloyTeam/AlloyImage#drawrect
