### ISSUE TITLE
`lineTo()`参数给定冗余

### ISSUE THREAD

**Issue by mapleeit** [AlloyTeam/AlloyImage#14]
```javascript
for(var i = 0; i < 255; i ++){
    var currY = result[i] || 0;
    currY = canvas.height - currY / max * 0.8 * canvas.height;
    context.lineTo(i / 256 * canvas.width, currY, 1, 1);  // 问题在本行
}
```
- 代码段位置：`alloyimage.base.js`（line：773）
- `context.lineTo()`函数指定两个参数，是不是应该修改为`context.lineTo(i / 256 * canvas.width, currY); `
- [参考](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineTo)

**Comment by dorsywang** [comment]
感谢 fixed
