### ISSUE TITLE
请问有没有办法在小程序中使用alloyImage?

### ISSUE THREAD

**Issue by cailven** [AlloyTeam/AlloyImage#34]
因为小程序中没有window，因此无法直接使用，请问有没有办法在小程序中使用alloyImage?

**Comment by honghu91** [comment]
暂时没有适配，是否可以帮忙适配下~

**Comment by cailven** [comment]
> 暂时没有适配，是否可以帮忙适配下~

行，那我fork一套后，回头comitte一个分支给你们
